name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-14, macos-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Swift 6.0
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.0"
    
    - name: Cache Swift Package Manager
      uses: actions/cache@v4
      with:
        path: |
          .build
          Package.resolved
        key: ${{ runner.os }}-spm-${{ hashFiles('Package.swift', 'Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v

    - name: Build release binary
      if: matrix.os == 'macos-latest'
      run: |
        swift build -c release --arch arm64
        mkdir -p build/release
        cp .build/arm64-apple-macosx/release/notify build/release/

    - name: Upload binary artifact
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: notify-arm64-binary
        path: build/release/notify
        retention-days: 7